on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GoLang setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go mod download

      - name: Run build
        run: go build -o build/ cmd/pleasant/pleasant.go

      - name: Run vet & lint
        run: |
          find . -type f -name "*.go" -printf %h\\n | uniq | xargs go vet
#          find . -type f -name "*.go" -printf %h\\n | uniq | xargs golint

#      - name: Run testing
#        run: go test ./test -v

      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: pleasant-linux-x86_64
          path: build/pleasant
