name: Main

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Environment Variables from Dotenv
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env

      - name: GoLang setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Install dependencies
        run: |
          echo "App version: ${{ env.APP_VERSION }}"
          go version
          go get -u golang.org/x/lint/golint
          go mod download

      - name: Run build
        run: go build -o build/ cmd/pleasant/pleasant.go

      - name: Run vet & lint
        run: |
          find . -type f -name "*.go" -printf %h\\n | uniq | xargs go vet
#          find . -type f -name "*.go" -printf %h\\n | uniq | xargs golint

#      - name: Run testing
#        run: go test ./test -v

      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: pleasant-${{ env.APP_VERSION }}-linux-x86_64
          path: build/pleasant

      - name: Release build snapshot
        uses: softprops/action-gh-release@v0.1.12
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          name: v${{ env.APP_VERSION }}-snapshot
          files: build/pleasant
